<!-- string -->
<?php
$x = "Darkwhale";
echo $x . "<br>";
var_dump($x);
?>
<br>
<!-- integer -->
<?php
$x = 254;
echo $x . "<br>";
var_dump($x);
?>
<br>
<!-- float -->
<?php
$x = 45.25;
echo $x . "<br>";
var_dump($x);
?>
<br>
<!-- boolean -->
<?php
$x = true;
echo $x . "<br>";
var_dump($x);
?>
--------------------------
<br>----------------
<!-- array-->
<?php
$x = "html css js";
echo $x . "<br>";
var_dump($x);
?>
<br>
<!-- null -->
<?php
$x = null;
echo $x . "<br>";
var_dump($x);
?>